zuul:
  sensitive-headers:
  routes:
    product: /myProduct/**
spring:
  application:
    name: api-getway
management:
  security:
    enabled: false    
ribbon:
  ReadTimeout: 5000
  SocketTimeout: 5000
